---
abstract: 'Ensures a CPAN distribution has consistent versioning.'
author:
  - 'Glenn Fowler <cebjyre@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-ConsistentVersion
provides:
  Test::ConsistentVersion:
    file: lib/Test/ConsistentVersion.pm
    version: v0.2.3
recommends:
  Test::Pod::Content: 0
requires:
  Test::Builder: 0.94
  autodie: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/cebjyre/Test-ConsistentVersion
version: v0.2.3
