---
abstract: 'Ensures a CPAN distribution has consistent versioning.'
author:
  - 'Glenn Fowler <cebjyre@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-ConsistentVersion
provides:
  Test::ConsistentVersion:
    file: lib/Test/ConsistentVersion.pm
    version: v0.3.1
recommends:
  Test::Pod::Content: '0'
requires:
  Test::Builder: '0.94'
  autodie: '0'
  perl: '5.006'
  version: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/cebjyre/Test-ConsistentVersion
version: v0.3.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
