---
abstract: 'Ensures a CPAN distribution has consistent versioning.'
author:
  - 'Glenn Fowler <cebjyre@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-ConsistentVersion
provides:
  Test::ConsistentVersion:
    file: lib/Test/ConsistentVersion.pm
    version: v0.3.0
recommends:
  Test::Pod::Content: '0'
requires:
  Test::Builder: '0.94'
  autodie: '0'
  version: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/cebjyre/Test-ConsistentVersion
version: v0.3.0
