---
name: Test-ConsistentVersion
version: v0.0.1
author:
  - 'Glenn Fowler <cebjyre@cpan.org>'
abstract: Ensures a CPAN distribution has consistent versioning.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::Builder: 0
  autodie: 0
  version: 0
configure_requires:
  Module::Build: 0.340201
provides:
  Test::ConsistentVersion:
    file: lib/Test/ConsistentVersion.pm
    version: v0.0.1
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
